// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhQzTi02wQdMpvqp9M7sJvVtCcfKDWG8',
    appId: '1:953866172661:web:7e26066454051b73e8adbc',
    messagingSenderId: '953866172661',
    projectId: 'intellideskisannoying',
    authDomain: 'intellideskisannoying.firebaseapp.com',
    databaseURL: 'https://intellideskisannoying-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intellideskisannoying.firebasestorage.app',
    measurementId: 'G-P66GEJ3R6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA97t8zp6_9NUEE1_ZG48-0ci7WxvOfkRQ',
    appId: '1:953866172661:android:f7d4407cdcd46d2de8adbc',
    messagingSenderId: '953866172661',
    projectId: 'intellideskisannoying',
    databaseURL: 'https://intellideskisannoying-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intellideskisannoying.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqIBgwrNMpg2Tvytr5DjHydsYVc2uulDk',
    appId: '1:953866172661:ios:b9a9ff7b1d02791ce8adbc',
    messagingSenderId: '953866172661',
    projectId: 'intellideskisannoying',
    databaseURL: 'https://intellideskisannoying-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intellideskisannoying.firebasestorage.app',
    iosBundleId: 'com.example.intellideskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqIBgwrNMpg2Tvytr5DjHydsYVc2uulDk',
    appId: '1:953866172661:ios:b9a9ff7b1d02791ce8adbc',
    messagingSenderId: '953866172661',
    projectId: 'intellideskisannoying',
    databaseURL: 'https://intellideskisannoying-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intellideskisannoying.firebasestorage.app',
    iosBundleId: 'com.example.intellideskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjhQzTi02wQdMpvqp9M7sJvVtCcfKDWG8',
    appId: '1:953866172661:web:4842ae9d00d1863de8adbc',
    messagingSenderId: '953866172661',
    projectId: 'intellideskisannoying',
    authDomain: 'intellideskisannoying.firebaseapp.com',
    databaseURL: 'https://intellideskisannoying-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intellideskisannoying.firebasestorage.app',
    measurementId: 'G-RJCCDR499Z',
  );
}
